# Generated by Django 4.2.11 on 2026-01-30 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortedurl',
            old_name='short_url',
            new_name='alias',
        ),
    ]
