# Generated by Django 4.2.11 on 2026-01-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_short_url_shortedurl_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedurl',
            name='no_of_clicks',
            field=models.IntegerField(null=True),
        ),
    ]
