# Generated by Django 4.2.11 on 2026-01-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_shortedurl_no_of_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortedurl',
            name='no_of_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
