# Generated by Django 4.2.11 on 2026-01-30 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0006_alter_additionaluserinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to=settings.AUTH_USER_MODEL),
        ),
    ]
